FROM java:8 

# Install maven
RUN apt-get update
RUN apt-get install -y maven
RUN apt-get install -y -f

# Create directory
RUN mkdir -p /usr/src/autocourt
WORKDIR /usr/src/autocourt

ADD target target
ADD autocourt.log autocourt.log

EXPOSE 4567 9222 4444

CMD ["/usr/lib/jvm/java-8-openjdk-amd64/bin/java", "-jar", "target/AutoCourt-1.0.jar"]
