FROM armv7/armhf-java8

# Install maven
RUN apt-get update
RUN apt-get install -y maven
RUN apt-get install -y -f

# Create directory
RUN mkdir -p /usr/src/autocourt
WORKDIR /usr/src/autocourt

ADD target target

EXPOSE 4567 9222 4444

CMD java -jar target/AutoCourt-1.0.jar
